version: "3"
services:
  master:
    image: "master:latest"
    ports:
      - "8080:8080"
    networks:
      - spark-net
    deploy:
      placement:
        constraints:
          - node.labels.role==master
  
  worker:
    image: "worker:latest"
    ports:
      - "8081:8081"
    environment:
      - CORES=2
      - MEMORY=2G
    deploy:
      placement:
        constraints:
          - node.labels.role==worker
        replicas: 2
    networks:
      - spark-net

networks:
  spark-net:
    driver: overlay
